### ISSUE TITLE
Good Work

### ISSUE THREAD

**Issue by marcussacana** [trigger-death/TriggersTools.CatSystem2#3]
Well, to begin with, I'm sorry for creating an invalid issue.
I just wanted to congratulate you for making these tools and the wiki.
I decided to comment just because I was happy to know that after about 5 years one of my tools was relevant to the learning of third parties, creating then something better implemented in relation to my original.
I found your project by chance after receiving a star in another project of mine, I went to explore your profile, something I usually do a lot.
I have said and repeated several times that many, if not most, of my tools are more of an aid to learning than something for practical use, I don't usually spend a lot of time putting touches on to make the tool usable/friendly.
And usually all I see is at most someone commenting on how sad the interface of my tools is. (lol)
So I was extremely happy to know that one of my children, specifically the Debug Patch, was a reference for another developer (after all that was one of my main goals), happy to know that it was even improved, after you dig deeper into the engine (which I hardly do). 
I am someone who loves and admires the open source community from the bottom of my heart, so I am happy to see that my work had an influence on it, no matter how trivial it was.
So good work on researching and improving the methods of dealing with this engine, even offering a wiki for anyone who wanted to learn, something I never feel excited to do thanks to my bad English.

Have a good day, when you read you can close the issue, if I notice that you are AFK and stay a few weeks open I will close or delete it just for the purpose of organizing your repository.

**Comment by trigger-segfault** [comment]
Thank you, reading this means so much ❤️ 
More than just the debug patch, the basis for learning the CST and CSTL file format was from your source. Along with the fact that Nekopara Vol.3 uses CatSystem 2, Nekopara Vol.3 has been extremely useful as its one of the few VNs I've found using CSTL features.

And I'm happy to keep the issue alive as closed.
